# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                # ('author_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('author_id', models.CharField(max_length=4)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('url', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                # ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=13)),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
                ('publisher_id', models.CharField(blank=True, max_length=5)),
                ('url', models.CharField(blank=True, max_length=80, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='Booksauthors',
            fields=[
                # ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13)),
                ('author_id', models.CharField(max_length=4)),
                ('seq_no', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'booksauthors',
            },
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                # ('publisher_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('publisher_id', models.CharField(max_length=5)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('url', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'publishers',
            },
        ),
    ]
