# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180131_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='author_id',
            new_name='author_id1',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='publisher_id',
            new_name='publisher_id1',
        ),
        migrations.RenameField(
            model_name='booksauthors',
            old_name='author_id',
            new_name='author_id1',
        ),
        migrations.RenameField(
            model_name='publishers',
            old_name='publisher_id',
            new_name='publisher_id1',
        ),
    ]
