# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20180131_1504'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Author',
        ),
        migrations.RenameModel(
            old_name='Publishers',
            new_name='Publisher',
        ),
        migrations.AddField(
            model_name='books',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Publisher'),
        ),
    ]
