# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 17:21
from __future__ import unicode_literals

from django.db import migrations

from books.models import Publisher,Book, Author, BooksAuthors

def migrate_book_authors(apps, schema_editor):
    booksauthors=BooksAuthors.objects.all()
    for ba in booksauthors:
        # ba.isbn
        # ba.author_id1
        if Book.objects.filter(isbn=ba.isbn).exists() and Author.objects.filter(author_id1=ba.author_id1).exists():
            b=Book.objects.filter(isbn=ba.isbn).first()
            b.authors.add(Author.objects.filter(author_id1=ba.author_id1).first())
            b.save()

    

class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20180131_1613'),
    ]

    operations = [
        migrations.RunPython(migrate_book_authors),
    ]
