# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20180131_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booksauthors',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='book',
            table='books_book',
        ),
    ]
