# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20180131_1737'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table=None,
        ),
        migrations.AlterModelTable(
            name='book',
            table=None,
        ),
        migrations.AlterModelTable(
            name='publisher',
            table=None,
        ),
    ]
