# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20180131_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('registered_users', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='pubdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='num_awards',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='books',
            field=models.ManyToManyField(to='books.Book'),
        ),
    ]
