# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 17:48
from __future__ import unicode_literals

from django.db import migrations
from books.models import Book, Author
import random
import datetime
from random import randrange
from datetime import timedelta

def get_random_rating():
    return random.randint(1,10)

def get_random_price():
    return random.randint(10, 100)

def get_random_age():
    return random.randint(15, 80)

def get_random_pubdate():
    # https://stackoverflow.com/questions/553303/generate-a-random-date-between-two-other-dates
    start = datetime.datetime.strptime('1/1/2008 1:30 PM', '%m/%d/%Y %I:%M %p')
    end = datetime.datetime.strptime('1/1/2017 4:50 AM', '%m/%d/%Y %I:%M %p')
    delta = end - start
    int_delta = (delta.days * 24 * 60 * 60) + delta.seconds
    random_second = randrange(int_delta)
    return (start + timedelta(seconds=random_second)).date()

def generate_random_book_fields_data(apps, schema_editor):
    books=Book.objects.all()
    for b in books:
        b.rating=get_random_rating()
        b.price=get_random_price()
        b.pubdate=get_random_pubdate()
        b.save()

def generate_random_author_fields_data(apps, schema_editor):
    authors=Author.objects.all()
    for a in authors:
        a.age=get_random_age()
        a.save()

class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20180131_1746'),
    ]

    operations = [
        migrations.RunPython(generate_random_book_fields_data, generate_random_author_fields_data),
    ]
